### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by Zemerik** [ParthJohri/voiceToText#1]
Hey, 

Can you deploy your website so that users can view your website?

Regards, 
Zemerik

**Comment by ParthJohri** [comment]
Hi @Zemerik ,

Sure, I would deploy it but as of now it does not do much, actually I made this project for just testing the speech recognition API.

**Comment by Zemerik** [comment]
oh ok. Thanks Parth

**Comment by ParthJohri** [comment]
@Zemerik I have deployed the project, you can check it over here - https://voice-to-text-tawny.vercel.app/

**Comment by ParthJohri** [comment]
@Zemerik I have deployed the project, you can check it over here - https://voice-to-text-tawny.vercel.app/

**Comment by Zemerik** [comment]
❤️Lovely Project
